// Fichier de donn茅es pour le catalogue Nexora
import { Product } from './types';

export const SCRAPED_PRODUCTS: Product[] = [
  {
    id: 'scr-cb-1' as any,
    name: 'ASUS Vivobook 15 - Intel Core i7 - 16 Go RAM - 512 Go SSD',
    description: 'Ordinateur portable performant et polyvalent. Parfait pour le d茅veloppement, la bureautique et le divertissement. 脡cran 15.6" Full HD avec traitement anti-reflets.',
    price: 749,
    imageUrl: 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=600&auto=format&fit=crop&q=80',
    category: 'ordinateurs',
    brand: 'ASUS',
    rating: 4.7,
    isPromo: true,
    featured: true,
    stock: 45,
    inStock: true,
    quantity: 45
  },
  {
    id: 'scr-cb-2' as any,
    name: 'Apple MacBook Air 13" Puce M3 - 8 Go - 256 Go SSD - Noir Minuit',
    description: 'Le MacBook Air avec puce M3 ultra-rapide. Design ultra-fin, bo卯tier en aluminium 100% recycl茅 et autonomie incroyable allant jusqu\'脿 18 heures.',
    price: 1199,
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    category: 'ordinateurs',
    brand: 'Apple',
    rating: 4.9,
    isPromo: false,
    featured: true,
    stock: 15,
    inStock: true,
    quantity: 15
  },
  {
    id: 'scr-cb-3' as any,
    name: 'iPhone 15 Pro 128 Go - Titane Naturel',
    description: 'Le tout premier iPhone avec un design en titane de qualit茅 a茅rospatiale, puce A17 Pro r茅volutionnaire et un syst猫me photo encore plus puissant.',
    price: 1049,
    imageUrl: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&auto=format&fit=crop&q=80',
    category: 't茅l茅phones',
    brand: 'Apple',
    rating: 4.8,
    isPromo: false,
    featured: true,
    stock: 22,
    inStock: true,
    quantity: 22
  },
  {
    id: 'scr-cb-4' as any,
    name: 'Samsung Galaxy S24 Ultra 256 Go - Noir Titane',
    description: 'D茅couvrez l\'era de l\'intelligence mobile avec Galaxy AI. Cadre en titane 茅l茅gant, stylet S Pen int茅gr茅 et capteur photo exceptionnel de 200 Mpx.',
    price: 1249,
    imageUrl: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=600&auto=format&fit=crop&q=80',
    category: 't茅l茅phones',
    brand: 'Samsung',
    rating: 4.7,
    isPromo: true,
    featured: false,
    stock: 35,
    inStock: true,
    quantity: 35
  },
  {
    id: 'scr-cb-5' as any,
    name: 'Sony WH-1000XM5 Casque Sans-fil 脿 R茅duction de Bruit Active',
    description: 'Casque audio circum-aural avec r茅duction de bruit sans pr茅c茅dent, un son haute r茅solution exceptionnel et un confort absolu.',
    price: 299,
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    category: 'audio',
    brand: 'Sony',
    rating: 4.9,
    isPromo: true,
    featured: true,
    stock: 60,
    inStock: true,
    quantity: 60
  },
  {
    id: 'scr-cb-6' as any,
    name: 'Logitech MX Master 3S Souris Sans-Fil Haute Pr茅cision',
    description: 'La souris ergonomique embl茅matique r茅invent茅e pour une pr茅cision et une r茅activit茅 instantan茅es. Id茅ale pour la productivit茅.',
    price: 109,
    imageUrl: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=600&auto=format&fit=crop&q=80',
    category: 'accessoires',
    brand: 'Logitech',
    rating: 4.8,
    isPromo: false,
    featured: true,
    stock: 120,
    inStock: true,
    quantity: 120
  },
  {
    id: 'scr-cb-7' as any,
    name: 'Samsung QLED 4K 55" Smart TV',
    description: 'Une qualit茅 d\'image 茅clatante avec des contrastes saisissants gr芒ce 脿 la technologie QLED. Acc茅dez 脿 toutes vos applications de streaming.',
    price: 699,
    imageUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?w=600&auto=format&fit=crop&q=80',
    category: 'tv & audio',
    brand: 'Samsung',
    rating: 4.6,
    isPromo: true,
    featured: true,
    stock: 14,
    inStock: true,
    quantity: 14
  }
];
